### ISSUE TITLE
Historical information about the FIWARE GE status

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-tsc-dashboard#12]
We want to keep the historical information of the FIWARE GE every week in order to make a representation of the information and see the evolution of the components.

**Comment by flopezag** [comment]
The idea is to automatically store the information in a InfluxDB historical database and from there recover the information in a Grafana instance to show the evolution in time of the different parameters.

**Comment by depa02** [comment]
A dedicated google sheets page has been created where manually data from "Catalogue", "Readthedocs", "Docker", "Github", and "Academy" are copied.

The google sheets is organised with a page for each data, and for each data a column for each day where data is collected.

The google sheets page is available at https://docs.google.com/spreadsheets/d/1foOMDZTu9ORU1ZyrriU9J3FEHV00UQub-lCIQseZCxY/edit#gid=1452860397

This is of course a temporary solution!

**Comment by flopezag** [comment]
Resolved with the commits 2ef2c82e3246cd70e8d91e71df8360da274f3b15 

Pending to update the content of configuration files. The periodical analysis is one week on Monday.
