### ISSUE TITLE
Update the list of Incubated, support, development and deprecated FIWARE GEis

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-tsc-dashboard#13]
We should update the content of the current FIWARE GEis with the last updated information.

**Comment by depa02** [comment]
This Issue includes also to add the counters for the newly added geris and for those that for some reasons still do not have them.

**Comment by flopezag** [comment]
The commit 59d7520 in develop resolves this issue, pending PR to deploy and test before closing this issue.

**Comment by flopezag** [comment]
Resolved in release v1.2.0
