### ISSUE TITLE
Update the content of file enablers.json, adding the new components

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-tsc-dashboard#36]
We need to update the content of the file [enablers.json](https://github.com/flopezag/fiware-tsc-dashboard/blob/master/config/enablers.json) with the current list of enablers and keeping the current one to dismissed or under support. The file is organized in alphabetical order grouped by status. The semantic of the keys is the following:

- **name**: Official full name of the component
- **status**: Current status of the component. Possible values:
    - Incubated, GE in process to be accepted into the community
    - Development, GE accepted and all the metrics are up & running
    - Support, GE that it is no more developed but still the community offers support on it
    - Quarantine, GE that it is advised to be deprecated if there is no proper activity on it (Support and/or development activities).
    - Deprecated, GE that it is no more under the scope of the FIWARE Catalogue
- **chapter**: Currently, it makes reference to the corresponding Jira Project in which the features, workitems and stories where stored to be executed during sprints. To be Deprecated, put in the meantime the value IoT
- **type**: what is the type of the GE (Product, Platform Component, Component or Service)
- **owner**: full name of the owner of the GE. It has to be aligned with the content of [owners.json](https://github.com/flopezag/fiware-tsc-dashboard/blob/master/config/owners.json) file

**Comment by caa06d9c** [comment]
The list of statues changed:
- full
- incubating
- deprecated
- quarantined

What should I do with support&development?

**Comment by caa06d9c** [comment]
Maybe it's better to refactor attributes? chapter - currently present as a list of values:

-  api-management
- core
- data-monetization
- data-publication
- deployment-tools
- iot-agents
- media-streams
- processing
- robotics
- security
- third-party
- visualization

Maybe attribute 'chapter' list should be expanded with values 'platform component, tool', etc, and attribute 'type' - removed?

**Comment by flopezag** [comment]
"support" || "deprecated" -> "deprecated"
"type" -> "blank" (pending to delete the content in the code properly)
"chapter" -> incubated, quarantine, and full with the new categorisation, the deprecated GEs leave blank

**Comment by caa06d9c** [comment]
resolved by https://github.com/flopezag/fiware-tsc-dashboard/pull/38
