### ISSUE TITLE
Update the content of metrics_endpoints.json

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-tsc-dashboard#37]
We need to update the content of the file [metrics_endpoints.json](https://github.com/flopezag/fiware-tsc-dashboard/blob/develop/config/metrics_endpoints.json) with the current list of enablers. The file is organized in alphabetical order of enabler key. The semantic of the keys is the following:

* **enabler**: Full name of the enabler. It has to be aligned with the key **"name"** in the file [enablers.json](https://github.com/flopezag/fiware-tsc-dashboard/blob/develop/config/enablers.json)
* **catalogue**: Name of the catalogue link of the **old** FIWARE Catalogue. Need to be changed to address the new Catalogue architecture. By default the new component assign the value **""**.
* **academy**: Name of the academy link of the **old** FIWARE Academy. Need to be changed to address the new Academy. By default the new component assign the value **""**.
* **readthedocs**: Name of the readthedocs page (e.g. fiware-idm is for the url https://fiware-idm.readthedocs.io)
* **github**: Github repository in the form "organization/repository"
* **docker**: name of the docker repository inside the fiware organization in which the GE is located.
* **helpdesk**: name of the HD-Enabler in the Jira Help-Desk (HELP) project
* **backlog**: To be modified, keep by default the value **""**
* **jira_workitem**: Deprecated to keep only the value **""**

**Comment by caa06d9c** [comment]
Academy. Some of GE has a link to the new academy at the readthedocs, like[ quantum-leap](https://fiware-academy.readthedocs.io/en/latest/core/quantum-leap/), should I use it?

Enabler. GE's names were changed, should I use a new one, like 

> Publish/Subscribe Context Broker - Orion Context Broker

to

> Orion Context Broker

GitHub and Docker. Can I use a list as a default value, even if only one entity exists?

**Comment by caa06d9c** [comment]
Resolved by https://github.com/flopezag/fiware-tsc-dashboard/pull/38
